package report

import (
	"fmt"
	"strings"
	"time"
)

// ExportMarkdown exports the report as markdown
func (g *Generator) ExportMarkdown(report *Report) string {
	var sb strings.Builder
	
	// Header
	sb.WriteString(fmt.Sprintf("# %s\n\n", report.Title))
	sb.WriteString(fmt.Sprintf("**Generated:** %s\n\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString("---\n\n")
	
	// Executive Summary
	sb.WriteString(report.Summary)
	sb.WriteString("\n---\n\n")
	
	// Methodology
	sb.WriteString(report.Methodology)
	sb.WriteString("\n---\n\n")
	
	// Findings
	if len(report.Findings) > 0 {
		sb.WriteString("## Findings\n\n")
		
		for i, finding := range report.Findings {
			sb.WriteString(fmt.Sprintf("### Finding %d: %s\n\n", i+1, finding.Title))
			sb.WriteString(fmt.Sprintf("**Severity:** %s\n\n", finding.Severity))
			sb.WriteString(fmt.Sprintf("**Description:**\n%s\n\n", finding.Description))
			
			if finding.Evidence != "" {
				sb.WriteString(fmt.Sprintf("**Evidence:**\n```\n%s\n```\n\n", finding.Evidence))
			}
			
			if finding.Command != "" {
				sb.WriteString(fmt.Sprintf("**Command Used:**\n```bash\n%s\n```\n\n", finding.Command))
			}
			
			if finding.Remediation != "" {
				sb.WriteString(fmt.Sprintf("**Remediation:**\n%s\n\n", finding.Remediation))
			}
			
			sb.WriteString("---\n\n")
		}
	}
	
	// Timeline
	if len(report.CommandTimeline) > 0 {
		sb.WriteString("## Command Timeline\n\n")
		sb.WriteString("| Time | Command | Exit Code | Duration (ms) |\n")
		sb.WriteString("|------|---------|-----------|---------------|\n")
		
		for _, cmd := range report.CommandTimeline {
			timeStr := cmd.StartTime.Format("15:04:05")
			commandStr := cmd.Command
			if len(commandStr) > 50 {
				commandStr = commandStr[:47] + "..."
			}
			sb.WriteString(fmt.Sprintf("| %s | `%s` | %d | %d |\n",
				timeStr, commandStr, cmd.ExitCode, cmd.Duration))
		}
		
		sb.WriteString("\n---\n\n")
	}
	
	// Recommendations
	if len(report.Recommendations) > 0 {
		sb.WriteString("## Recommendations\n\n")
		for i, rec := range report.Recommendations {
			sb.WriteString(fmt.Sprintf("%d. %s\n", i+1, rec))
		}
		sb.WriteString("\n")
	}
	
	// Footer
	sb.WriteString("---\n\n")
	sb.WriteString(fmt.Sprintf("*Report generated by BlackBook Penetration Testing Toolkit*\n"))
	
	return sb.String()
}

// ExportHTML exports the report as HTML (basic implementation)
func (g *Generator) ExportHTML(report *Report) string {
	markdown := g.ExportMarkdown(report)
	
	// Basic HTML wrapper
	var sb strings.Builder
	sb.WriteString("<!DOCTYPE html>\n")
	sb.WriteString("<html>\n<head>\n")
	sb.WriteString(fmt.Sprintf("<title>%s</title>\n", report.Title))
	sb.WriteString("<style>\n")
	sb.WriteString("body { font-family: Arial, sans-serif; max-width: 900px; margin: 50px auto; padding: 20px; }\n")
	sb.WriteString("h1 { color: #2c3e50; }\n")
	sb.WriteString("h2 { color: #34495e; border-bottom: 2px solid #ecf0f1; padding-bottom: 10px; }\n")
	sb.WriteString("pre { background: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; }\n")
	sb.WriteString("table { width: 100%; border-collapse: collapse; margin: 20px 0; }\n")
	sb.WriteString("th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }\n")
	sb.WriteString("th { background-color: #3498db; color: white; }\n")
	sb.WriteString(".critical { color: #e74c3c; font-weight: bold; }\n")
	sb.WriteString(".high { color: #e67e22; font-weight: bold; }\n")
	sb.WriteString(".medium { color: #f39c12; font-weight: bold; }\n")
	sb.WriteString(".low { color: #27ae60; font-weight: bold; }\n")
	sb.WriteString("</style>\n")
	sb.WriteString("</head>\n<body>\n")
	
	// Simple markdown to HTML conversion (basic)
	htmlContent := strings.ReplaceAll(markdown, "\n\n", "</p><p>")
	htmlContent = strings.ReplaceAll(htmlContent, "\n", "<br>")
	htmlContent = "<p>" + htmlContent + "</p>"
	
	sb.WriteString(htmlContent)
	sb.WriteString("\n</body>\n</html>")
	
	return sb.String()
}

// Template constants
const (
	DefaultReportTemplate = "default"
	DetailedReportTemplate = "detailed"
	ExecutiveSummaryTemplate = "executive"
)
