// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCommand(arg1) {
  return window['go']['main']['App']['AddCommand'](arg1);
}

export function AnalyzeCommand(arg1) {
  return window['go']['main']['App']['AnalyzeCommand'](arg1);
}

export function CheckOllamaStatus() {
  return window['go']['main']['App']['CheckOllamaStatus']();
}

export function ExportReport(arg1) {
  return window['go']['main']['App']['ExportReport'](arg1);
}

export function GenerateScript(arg1) {
  return window['go']['main']['App']['GenerateScript'](arg1);
}

export function GetAISuggestion() {
  return window['go']['main']['App']['GetAISuggestion']();
}

export function GetCommandHistory() {
  return window['go']['main']['App']['GetCommandHistory']();
}

export function GetCurrentReport() {
  return window['go']['main']['App']['GetCurrentReport']();
}

export function GetTerminalOutput() {
  return window['go']['main']['App']['GetTerminalOutput']();
}

export function ResizeTerminal(arg1, arg2) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function UpdateCommandOutput(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCommandOutput'](arg1, arg2, arg3);
}

export function WriteToTerminal(arg1) {
  return window['go']['main']['App']['WriteToTerminal'](arg1);
}
